version: '3.8'

services:
  order-service:
    build: .
    ports:
      - "8081:8081"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/ordersdb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
